package engine

// ConditionLet is ...
type ConditionLet string

const (
	// EQUAL represents ...
	EQUAL ConditionLet = "EQUAL"
	// NEQUAL represents ...
	NEQUAL ConditionLet = "NOT EQUAL"
	// EXIST represents ...
	EXIST ConditionLet = "EXIST"
	// NEXIST represents ...
	NEXIST ConditionLet = "NOT EXIST"
)
